### ISSUE TITLE
Open code

### ISSUE THREAD

**Issue by trangdata** [bdawkins99/BoD#3]
Could we make the code publicly available? I understand this is a theoretical paper and most of the code is for generating figures, but this will help increase reproducibility! Thanks!

**Comment by bdawkins99** [comment]
Hey Trang, I have been meaning to add code for all of the results/figures in the text so far. I am currently working on a new simulation method for mixed effects that should be done soon. I will add legible versions of the code I have been using soon. Thanks!

**Comment by trangdata** [comment]
Code published so I'm closing.
