### ISSUE TITLE
Conflicts on one paragraph

### ISSUE THREAD

**Issue by trangdata** [bdawkins99/BoD#8]
@bdawkins99  Could you please check the following commit whether this is correct? I was experiencing some merge conflicts.
https://github.com/bdawkins99/BoD/commit/dfa180575411503860862157944a8b7a030297f4

**Comment by bdawkins99** [comment]
@trang1618 I don't see anything incorrect about the commit, but I am also still moderately git illiterate. Are you still having merge conflicts?

**Comment by trangdata** [comment]
No I no longer have conflicts. I weren't sure if you added the other paragraph or deleted it, so I wanted to make sure. Thank you!
